### PR TITLE
Add information for presetup

### PR DESCRIPTION
**Pull request by InsanusMokrassar**

### CODE REVIEW

**Comment by InsanusMokrassar** [comment]
@Ingvord could you, please, review this PR

**Comment by Ingvord** [comment]
@InsanusMokrassar thanx for the PR!

Please add `Ready for Merge` label when you finish with this PR, Or is it ready?

**Comment by InsanusMokrassar** [comment]
I can't add any labels for now, but I have removed redundant note about npm. Let me check that it is correctly compiling

**Comment by InsanusMokrassar** [comment]
@Ingvord it is ready for merge

**Pull request merged**
